Create a numpy array with filling random values, and shape of array
should be (12,5), and pass this array from a user-defined function, and
function should be able to return average, minimum, maximum, and
no. of evens in your last row.
For e.g. consider this is last row [41,52,63,96,85],
Output:
Average -> 67.4
Minimum -> 41
Maximum -> 96
No. of evens -> 2

In [2]:
import numpy as np

In [11]:

def array_state():
    arr = np.random.randint(1, 100, 60).reshape(12, 5)
    print(arr)

    last_row = arr[-1]

    avg = np.mean(last_row)
    max_val = np.max(last_row)
    min_val = np.min(last_row)
    even_count = np.sum(last_row % 2 == 0)

    return avg, max_val, min_val, even_count


avg, max_val, min_val, even_count = array_state()

# Print the results
print("Average of last row: ", avg)
print("Max element of last row: ", max_val)
print("Min element of last row: ", min_val)
print("No. of even in last row: ", even_count)


[[62 61 34 48 35]
 [17  2 21 13 80]
 [ 8 25 53 60 47]
 [83 62 50 48 28]
 [32 15 27 81 51]
 [33  1 24 36 90]
 [66 93 37 15  8]
 [51 96 92 11 63]
 [78 16 73  7 39]
 [40 73 37 95 31]
 [39 93 10 40 87]
 [34  4 91 81 98]]
Average of last row:  61.6
Max element of last row:  98
Min element of last row:  4
No. of even in last row:  3


Let’s consider we have an array, e.g.
[[1 2 3 ],
[4 5 6 ],
[7 8 9 ]]
And apply slicing techniques to get reversed order elements of all the rows,
like this -> [[3 2 1],
 [6 5 4],
 [9 8 7]]


In [39]:
arr2 = np.random.randint(1,10,(3,3))
print("Original Array : \n",arr2)

reversed_array = arr2[0:3, ::-1]

print("Reversed Array : \n",reversed_array)

Original Array : 
 [[4 9 3]
 [2 2 1]
 [1 2 9]]
Reversed Array : 
 [[3 9 4]
 [1 2 2]
 [9 2 1]]
