Create a numpy array with filling random values, and shape of array
should be (12,5), after that manipulate the value of last row.
For e.g. let’s consider this is your last row [41,52,63,96,85], you will
update this line like this [1,2,3,4,5]

In [1]:
import numpy as np


In [26]:

arr = np.random.randint(1, 100, 60).reshape(12,5)
print("Array without change : \n" ,arr)
print("\n")

new_values_str = input("Enter 5 values separated by spaces for the last row: ")
new_values = list(map(int, new_values_str.split()))
arr[-1] = np.array(new_values) 
# arr[-1] = np.array([1,2,3,4,5])

print("Array after change last row \n",arr)

Array without change : 
 [[45 55 25 10 84]
 [55 86  9 95 14]
 [25 23 55 72 74]
 [30 71 50 83 46]
 [74 28 36 41 44]
 [96 52 23 89 61]
 [30 44 60 84 32]
 [51 33 61 90 87]
 [42 34  8 81 14]
 [66 65 29 66 58]
 [77 80 84 50 71]
 [ 6 26 34 61 82]]


Array after change last row 
 [[45 55 25 10 84]
 [55 86  9 95 14]
 [25 23 55 72 74]
 [30 71 50 83 46]
 [74 28 36 41 44]
 [96 52 23 89 61]
 [30 44 60 84 32]
 [51 33 61 90 87]
 [42 34  8 81 14]
 [66 65 29 66 58]
 [77 80 84 50 71]
 [ 1  2  3  4  5]]


Write a python function to find the minimum and maximum elements
in each and every row of numpy array, and create numpy array with
filling random integer value, and shape of array should be (12,5),
For e.g. I took first row from
2D array [21,4,3,62,52,1] so 1 is minimum and 52 is maximum in this
row. So your python function should return this output for each and
every row

In [36]:
arr1 = np.random.randint(1,100,60).reshape(12,5)

for i in arr1 :
    max = i[0]
    for j in i :
        if j > max :
            max = j
    print("Max element in Row " ,i ," is : ", max)
print("\n")

for i in arr1 :
    min = i[0]
    for j in i :
        if j < min :
            min = j
    print("Min element in Row " ,i ," is : ", min)

Max element in Row  [80 29 26 95 37]  is :  95
Max element in Row  [55 37 96 75 51]  is :  96
Max element in Row  [39 11 17 44 10]  is :  44
Max element in Row  [58 40 39 79 63]  is :  79
Max element in Row  [45  4 75 68 95]  is :  95
Max element in Row  [17 52 32 40 75]  is :  75
Max element in Row  [86 85 95 83 39]  is :  95
Max element in Row  [37 11 73 88 43]  is :  88
Max element in Row  [50 88  7 50 29]  is :  88
Max element in Row  [ 7 97 40 23 64]  is :  97
Max element in Row  [13 13 95 50 34]  is :  95
Max element in Row  [29 35 78 76 26]  is :  78


Min element in Row  [80 29 26 95 37]  is :  26
Min element in Row  [55 37 96 75 51]  is :  37
Min element in Row  [39 11 17 44 10]  is :  10
Min element in Row  [58 40 39 79 63]  is :  39
Min element in Row  [45  4 75 68 95]  is :  4
Min element in Row  [17 52 32 40 75]  is :  17
Min element in Row  [86 85 95 83 39]  is :  39
Min element in Row  [37 11 73 88 43]  is :  11
Min element in Row  [50 88  7 50 29]  is :  7
Min element i